

service: tasks-backend-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  #lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless

package:
  artifact: target/tasks-api-java-dev.jar

functions:
  get-tasks-api:
    handler: com.serverless.GetTasksHandler

    events:
      - http:
          path: users/{userId}/task
          method: get

